name: Auto-Clean

on:
  #自动清理：每天早上7点
  schedule:
    - cron: 0 7 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           repository: ${{ github.repository }}
           retain_days: 0
           keep_minimum_runs: 2
