name: Delete Workflows

on:
  repository_dispatch:
  workflow_dispatch:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed
    branches:
      - main

jobs:
  delete-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: 获取工作流 ID
        id: get-workflow-id
        uses: actions/github-script@v4
        with:
          script: |
            token: ${{ secrets.GITHUB_TOKEN }}
            const { data } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              per_page: 1
            });
            console.log(`Workflow ID: ${data.workflow_runs[0].id}`);
            return data.workflow_runs[0].id

      - name: 删除工作流
        uses: actions/github-script@v4
        with:
          script: |
            token: ${{ secrets.GITHUB_TOKEN }}
            const runId = ${{ steps.get-workflow-id.outputs.id }};
            await github.actions.deleteWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
