name: Delete Workflows

on:
  repository_dispatch:
  workflow_dispatch:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed
    branches:
      - main
jobs:
  delete-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2
