name: Delete Workflows

on:
  workflow_run:
    workflows:
      - 'Delete Workflows'
    types:
      - completed
    branches:
      - main

jobs:
  delete-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Get Workflow List
        uses: actions/github-script@v4
        with:
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const completedWorkflows = workflows.filter(workflow => workflow.status === 'completed');
            const failedWorkflows = workflows.filter(workflow => workflow.status === 'failed');

            const workflowsToDelete = workflows.filter(workflow => !completedWorkflows.includes(workflow) && !failedWorkflows.includes(workflow));

            for (const workflow of workflowsToDelete) {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflow.id
              });
            }
