name: Delete Workflows

on:
  workflow_dispatch:
  schedule:
    # 每天凌晨执行一次
    - cron: '0 0 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq


      - name: Cleanup workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取当前仓库的所有工作流运行
          runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs?per_page=100" | jq '.workflow_runs')

          # 保留最近两条状态为运行完成的工作流
          completed_runs=$(echo $runs | jq '.[] | select(.conclusion == "success" or .conclusion == "failure") | .id' | sort -n | tail -n 2)
          for run_id in $completed_runs; do
            echo "保留完成的工作流: $run_id"
          done

          # 保留最近两条状态为未完成的工作流
          pending_runs=$(echo $runs | jq '.[] | select(.conclusion == "neutral" or .conclusion == "cancelled" or .conclusion == "timed_out" or .conclusion == "action_required") | .id' | sort -n | tail -n 2)
          for run_id in $pending_runs; do
            echo "保留未完成的工作流: $run_id"
          done

          # 删除其他所有工作流
          other_runs=$(echo $runs | jq '.[] | select(.id != $completed_runs[0] and .id != $completed_runs[1] and .id != $pending_runs[0] and .id != $pending_runs[1]) | .id')
          for run_id in $other_runs; do
            echo "删除工作流: $run_id"
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/$run_id"
          done
