name: Update Checker

env:
  REPO_URL_1: https://github.com/coolsnowwolf/lede
  REPO_BRANCH_1: master
  REPO_URL_2: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH_2: master

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */18 * * *'  # 每 18 小时运行一次

jobs:
  check-repo-1:
    runs-on: ubuntu-latest

    steps:
    - name: Get Commit Hash for Repo 1
      id: getHashRepo1
      run: |
        git clone --depth 1 ${{ env.REPO_URL_1 }} -b ${{ env.REPO_BRANCH_1 }} repo1
        cd repo1
        echo "commitHash1=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash for Repo 1
      id: cacheHashRepo1
      uses: actions/cache@v4
      with:
        path: .commitHashRepo1
        key: commitHashRepo1_${{ steps.getHashRepo1.outputs.commitHash1 }}

    - name: Save New Commit Hash for Repo 1
      if: steps.cacheHashRepo1.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHashRepo1.outputs.commitHash1 }} | tee .commitHashRepo1

    - name: Generate configuration file for Repo 1
      if: steps.cacheHashRepo1.outputs.cache-hit != 'true'
      run: |
        cd repo1
        make defconfig

    - name: Trigger build for Repo 1
      if: steps.cacheHashRepo1.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: update_${{ event_type }}

  check-repo-2:
    runs-on: ubuntu-latest

    steps:
    - name: Get Commit Hash for Repo 2
      id: getHashRepo2
      run: |
        git clone --depth 1 ${{ env.REPO_URL_2 }} -b ${{ env.REPO_BRANCH_2 }} repo2
        cd repo2
        echo "commitHash2=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash for Repo 2
      id: cacheHashRepo2
      uses: actions/cache@v4
      with:
        path: .commitHashRepo2
        key: commitHashRepo2_${{ steps.getHashRepo2.outputs.commitHash2 }}

    - name: Save New Commit Hash for Repo 2
      if: steps.cacheHashRepo2.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHashRepo2.outputs.commitHash2 }} | tee .commitHashRepo2

    - name: Generate configuration file for Repo 2
      if: steps.cacheHashRepo2.outputs.cache-hit != 'true'
      run: |
        cd repo2
        make defconfig

    - name: Trigger build for Repo 2
      if: steps.cacheHashRepo2.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: update_${{ github.run_id }}_${{ github.run_number }}

  delete-old-runs:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        retain_days: 0
        keep_minimum_runs: 2
