name: X

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt

jobs:
  print_repo_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run: |
          repo_url=${{ env.REPO_URL }}
          repo_name=$(basename $repo_url)
          echo "Repository name: $repo_name $"
