name: Delete Old Workflows
on:
  schedule:
    - cron: '*/10 * * * *'  # 每天运行一次
  workflow_dispatch:

jobs:
  delete_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Workflows
        id: list_workflows
        run: |
          echo "::set-output name=completed_workflows::$(gh workflow list --json 'status=completed' --jq '.[].id' | head -n -2 | tr 'n' ',')"
          echo "::set-output name=failed_workflows::$(gh workflow list --json 'status=failed' --jq '.[].id' | head -n -2 | tr 'n' ',')"

      - name: Delete Workflows
        env:
          COMPLETED_WORKFLOWS: ${{ steps.list_workflows.outputs.completed_workflows }}
          FAILED_WORKFLOWS: ${{ steps.list_workflows.outputs.failed_workflows }}
        run: |
          IFS=',' read -ra COMPLETED_WORKFLOWS_ARRAY <<< "$COMPLETED_WORKFLOWS"
          IFS=',' read -ra FAILED_WORKFLOWS_ARRAY <<< "$FAILED_WORKFLOWS"

          for workflowId in "${COMPLETED_WORKFLOWS_ARRAY[@]}"; do
            echo "Deleting completed workflow: $workflowId"
            gh workflow run delete --workflow-id "$workflowId" --confirm
          done

          for workflowId in "${FAILED_WORKFLOWS_ARRAY[@]}"; do
            echo "Deleting failed workflow: $workflowId"
            gh workflow run delete --workflow-id "$workflowId" --confirm
          done
