name: Delete Workflows

on:
  schedule:
    - cron: '*/10 * * * *'  # 每天运行一次
  workflow_dispatch:

jobs:
  delete_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Workflow List
        id: workflow_list
        run: |
          TOKEN=$TOKEN
          OWNER=$OWNER
          REPO=$REPO
          API_URL="https://api.github.com/repos/$OWNER/$REPO/actions/workflows"
          RESPONSE=$(curl -s -H "Authorization: token $TOKEN" $API_URL)
          echo "::set-output name=workflow_list::$RESPONSE"

      - name: Filter Completed Workflows
        id: completed_workflows
        run: |
          WORKFLOW_LIST=$WORKFLOW_LIST
          COMPLETED_WORKFLOWS=$(echo $WORKFLOW_LIST | jq '.workflows | map(select(.status == "completed")) | sort_by(.completed_at) | reverse | .[:2]')
          echo "::set-output name=completed_workflows::$COMPLETED_WORKFLOWS"

      - name: Filter Error Workflows
        id: error_workflows
        run: |
          WORKFLOW_LIST=$WORKFLOW_LIST
          ERROR_WORKFLOWS=$(echo $WORKFLOW_LIST | jq '.workflows | map(select(.status == "error")) | sort_by(.created_at) | reverse | .[:2]')
          echo "::set-output name=error_workflows::$ERROR_WORKFLOWS"

      - name: Delete Other Workflows
        id: delete_other_workflows
        run: |
          TOKEN=$TOKEN
          OWNER=$OWNER
          REPO=$REPO
          WORKFLOW_LIST=$WORKFLOW_LIST
          COMPLETED_WORKFLOWS=$COMPLETED_WORKFLOWS
          ERROR_WORKFLOWS=$ERROR_WORKFLOWS
          for WORKFLOW in $(echo $WORKFLOW_LIST | jq -r '.workflows[] | .id'); do
            if [[ "$WORKFLOW" != $(echo $COMPLETED_WORKFLOWS | jq -r '.[].id') ]] && [[ "$WORKFLOW" != $(echo $ERROR_WORKFLOWS | jq -r '.[].id') ]]; then
              curl -s -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW"
            fi
          done

      - name: Print Success Message
        if: steps.delete_other_workflows.outcome == 'success'
        run: echo "Workflows deleted successfully!"

      - name: Print Failure Message
        if: steps.delete_other_workflows.outcome == 'failure'
        run: echo "Failed to delete workflows!"
